Common services 1.0.8 (#52)
* Updates

1. Updated configmap for curator
2. Add a helper template
3. Updated values.yaml , curator section

* Updates

1. Updates to curator
2. Added comments to values.yaml
3. Added comments to chart.yaml
4. Updated app and chart versions (bumped the version number up)

* Updates

1. Updated notes.txt
2. Updated configmap to hardcode the name of configmap to reference elsewhere

* zoonavigator port 9000

* Remove "monitoring" tag from config and controller dashboards not really useful through EOC

* Add missing database dashboard

* Remove prometheus alerts manager as data source in grafana

* add index pattern for IA GIT Sync Service

* Updates

1. Updated the job and configmap for kibana and elastic to import saved objects if auth is enabled/disabled

* README UPDATE

* Removed #

* add CNPG operator (disabled by default)

* Modified values.yaml

modified values.yaml to pass the lint test

* add missing helm deps in lint test

* Update

1. Modified the configmap and job
2. Added a init container to the job to check kibana readiness
3. Added example to values.yaml to enable security on elastic

* Update

* Update

1. Modified kibana job

---------

Co-authored-by: pgodey <38923355+pgodey@users.noreply.github.com>
Co-authored-by: Jean-Michel Corné <jmcorne@radiantlogic.com>

diff --git a/charts/common-services/templates/kibana/kibana-config-map.yaml b/charts/common-services/templates/kibana/kibana-config-map.yaml
--- a/charts/common-services/templates/kibana/kibana-config-map.yaml
+++ b/charts/common-services/templates/kibana/kibana-config-map.yaml
@@ -1,51 +1,59 @@
-{{- if eq .Values.kibana.enabled true }}
+{{- if .Values.kibana.enabled }}
 apiVersion: v1
 kind: ConfigMap
 metadata:
   name: kibana-data
 data:
-
   curl-script.sh: |
     #!/bin/sh
+    set -e
 
-    function import_index {
-        echo "Importing Index-Patterns"
-        echo "The curl command creates symlinks so using an alternative method"
-        echo "Copying the Index-Pattern file from /kibana/index_pattern to /opt/index_pattern to make it hardlink"
-        cat /kibana/index_pattern.ndjson > /opt/index_pattern.ndjson
-        response=""
-        success="false"
-        until [[ "$success" == "true" ]]; do
-            response=$(curl -s --location --request POST "${KIBANA_URL}/api/saved_objects/_import?overwrite=true" \
-                            --header 'kbn-xsrf: true' \
-                            --form 'file=@"/opt/index_pattern.ndjson"' | jq '.')
-            success=$(echo "$response" | jq -r '.success')
+    MAX_ATTEMPTS=5
+    SLEEP_DURATION=5
+
+    import_index() {
+        echo "Starting the import of index patterns."
+        local file_path="/tmp/index_pattern.ndjson"
+        echo "Copying index pattern file to a temporary location to avoid symlink issues."
+        cp /kibana/index_pattern.ndjson $file_path
+
+        local import_success="false"
+        local attempt=0
+
+        while [ "$import_success" != "true" ] && [ $attempt -lt $MAX_ATTEMPTS ]; do
+            attempt=$((attempt + 1))
+            echo "Attempt $attempt of $MAX_ATTEMPTS"
+
+            local auth_header=""
+            if [ "${AUTH_ENABLED}" = "true" ]; then
+                auth_header="Authorization: Basic $(echo -n "${ELASTICSEARCH_USERNAME}:${ELASTICSEARCH_PASSWORD}" | base64)"
+            fi
+
+            local response=$(curl -s --location --request POST "${KIBANA_URL}/api/saved_objects/_import?overwrite=true" \
+                              --header 'kbn-xsrf: true' \
+                              --header "${auth_header}" \
+                              --form "file=@$file_path")
+            import_success=$(echo "$response" | grep -q '"success":true' && echo "true" || echo "false")
+
             echo "Response: $response"
-            sleep 5
+            if [ "$import_success" != "true" ]; then
+                echo "Error: Failed to import index patterns. Retrying in $SLEEP_DURATION seconds..."
+                sleep $SLEEP_DURATION
+            fi
         done
-        if [[ "$success" == "true" ]]; then
-            printf "\nThe Kibana Index Patterns have been successfully imported\n"
+
+        if [ "$import_success" = "true" ]; then
+            echo "Successfully imported index patterns."
         else
-            printf "\nFailure while importing index-pattern\n"
-            echo "Details: $(echo "$response" | jq '.errors[]')"
+            echo "Failed to import index patterns after $MAX_ATTEMPTS attempts."
+            echo "Details: $response"
+            exit 1
         fi
     }
 
-    while true
-    do
-      if [[ $(curl -s ${KIBANA_URL}/api/status | jq -r .status.overall.state) == "green" ]]; then
-        echo "kibana is healthy"
-        import_index
-        break
-      else
-        echo "kibana is unhealthy"
-      fi
-    sleep 5
-    done
+    import_index
+
 
   index_pattern.ndjson: |
 {{ .Files.Get "dashboards/kibana-index-pattern.ndjson" | indent 4 }}
-
-
 {{- end }}
-
